//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/SharedProject/codeCrackers/GameAssets/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""CameraMotionMap"",
            ""id"": ""3046892c-3387-4c4f-aaf1-8454565fcaca"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""e3bf340c-9b18-4ca9-b41f-f33716d30423"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""56286327-5e54-45e7-ba45-646cfd91123b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseClicked"",
                    ""type"": ""Button"",
                    ""id"": ""f5dffcd5-cc2e-487b-b743-4daa721b6be0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ModKey"",
                    ""type"": ""Button"",
                    ""id"": ""94c4501b-05a0-4e60-9da9-1cc41a1c8d5e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseClicked"",
                    ""type"": ""Button"",
                    ""id"": ""6eb1a11f-a865-484c-811a-349edae0e556"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""20a196ef-ab58-40aa-819d-a502cd1da1eb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""836ef66c-738c-4b68-bb53-2670857e369a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ddfb60db-7af5-46dc-8947-b1d488aca761"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b46ad2e6-e838-41e5-a11a-081d5ff04683"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2b109614-4cc6-42ce-af8a-4d9c6d59d407"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1650756f-2252-4197-9441-c353dd13cd0e"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f6af379-ba5a-46f1-9b0a-f294931feb13"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf538b18-8bfa-4f0f-8a91-059a5badfbb7"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ModKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93f5962e-7ed1-43bb-ad96-7d6bfac11932"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CameraMotionMap
        m_CameraMotionMap = asset.FindActionMap("CameraMotionMap", throwIfNotFound: true);
        m_CameraMotionMap_Movement = m_CameraMotionMap.FindAction("Movement", throwIfNotFound: true);
        m_CameraMotionMap_MousePos = m_CameraMotionMap.FindAction("MousePos", throwIfNotFound: true);
        m_CameraMotionMap_MouseClicked = m_CameraMotionMap.FindAction("MouseClicked", throwIfNotFound: true);
        m_CameraMotionMap_ModKey = m_CameraMotionMap.FindAction("ModKey", throwIfNotFound: true);
        m_CameraMotionMap_RightMouseClicked = m_CameraMotionMap.FindAction("RightMouseClicked", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraMotionMap
    private readonly InputActionMap m_CameraMotionMap;
    private List<ICameraMotionMapActions> m_CameraMotionMapActionsCallbackInterfaces = new List<ICameraMotionMapActions>();
    private readonly InputAction m_CameraMotionMap_Movement;
    private readonly InputAction m_CameraMotionMap_MousePos;
    private readonly InputAction m_CameraMotionMap_MouseClicked;
    private readonly InputAction m_CameraMotionMap_ModKey;
    private readonly InputAction m_CameraMotionMap_RightMouseClicked;
    public struct CameraMotionMapActions
    {
        private @PlayerControls m_Wrapper;
        public CameraMotionMapActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CameraMotionMap_Movement;
        public InputAction @MousePos => m_Wrapper.m_CameraMotionMap_MousePos;
        public InputAction @MouseClicked => m_Wrapper.m_CameraMotionMap_MouseClicked;
        public InputAction @ModKey => m_Wrapper.m_CameraMotionMap_ModKey;
        public InputAction @RightMouseClicked => m_Wrapper.m_CameraMotionMap_RightMouseClicked;
        public InputActionMap Get() { return m_Wrapper.m_CameraMotionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraMotionMapActions set) { return set.Get(); }
        public void AddCallbacks(ICameraMotionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraMotionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraMotionMapActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MousePos.started += instance.OnMousePos;
            @MousePos.performed += instance.OnMousePos;
            @MousePos.canceled += instance.OnMousePos;
            @MouseClicked.started += instance.OnMouseClicked;
            @MouseClicked.performed += instance.OnMouseClicked;
            @MouseClicked.canceled += instance.OnMouseClicked;
            @ModKey.started += instance.OnModKey;
            @ModKey.performed += instance.OnModKey;
            @ModKey.canceled += instance.OnModKey;
            @RightMouseClicked.started += instance.OnRightMouseClicked;
            @RightMouseClicked.performed += instance.OnRightMouseClicked;
            @RightMouseClicked.canceled += instance.OnRightMouseClicked;
        }

        private void UnregisterCallbacks(ICameraMotionMapActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MousePos.started -= instance.OnMousePos;
            @MousePos.performed -= instance.OnMousePos;
            @MousePos.canceled -= instance.OnMousePos;
            @MouseClicked.started -= instance.OnMouseClicked;
            @MouseClicked.performed -= instance.OnMouseClicked;
            @MouseClicked.canceled -= instance.OnMouseClicked;
            @ModKey.started -= instance.OnModKey;
            @ModKey.performed -= instance.OnModKey;
            @ModKey.canceled -= instance.OnModKey;
            @RightMouseClicked.started -= instance.OnRightMouseClicked;
            @RightMouseClicked.performed -= instance.OnRightMouseClicked;
            @RightMouseClicked.canceled -= instance.OnRightMouseClicked;
        }

        public void RemoveCallbacks(ICameraMotionMapActions instance)
        {
            if (m_Wrapper.m_CameraMotionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraMotionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraMotionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraMotionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraMotionMapActions @CameraMotionMap => new CameraMotionMapActions(this);
    public interface ICameraMotionMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
        void OnMouseClicked(InputAction.CallbackContext context);
        void OnModKey(InputAction.CallbackContext context);
        void OnRightMouseClicked(InputAction.CallbackContext context);
    }
}
